# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 474f304597d2c616a0cc0cc07c46220aaeb119eba08182f6b6642a8144099bad9930df2aad3c8520d0b002fcb376d381597ca4b7c5b6765d69355a68a085616b

test:
  secret_key_base: ecc783d73c00088d0845fbbef43ea103ab6f27ed7df92738b561b41f28f0ea0d4a205b32642c711af94892ed95bf48989b03cbb7741f65efbabc7943af50cc80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
